export const listMaterias = [
    {
        id: 1,
        code: "EC101",
        name: "Introdução à Engenharia de Computação",
        totalHours: 60,
        period: 1,
        active: false,
        viewed: true,
        requirements: [],
    },
    {
        id: 2,
        code: "EC102",
        name: "Matemática para Engenharia",
        totalHours: 90,
        period: 1,
        active: false,
        viewed: true,
        requirements: [],
    },
    {
        id: 3,
        code: "EC103",
        name: "Programação I",
        totalHours: 90,
        period: 1,
        active: false,
        viewed: true,
        requirements: [],
    },
    {
        id: 4,
        code: "EC104",
        name: "Física para Engenharia",
        totalHours: 90,
        period: 1,
        active: false,
        viewed: true,
        requirements: [],
    },
    {
        id: 5,
        code: "EC105",
        name: "Circuitos Elétricos",
        totalHours: 90,
        period: 2,
        active: false,
        viewed: false,
        requirements: [4],
    },
    {
        id: 6,
        code: "EC106",
        name: "Algoritmos e Estruturas de Dados",
        totalHours: 90,
        period: 2,
        active: false,
        viewed: false,
        requirements: [1, 3],
    },
    {
        id: 7,
        code: "EC107",
        name: "Cálculo Numérico",
        totalHours: 60,
        period: 2,
        active: false,
        viewed: false,
        requirements: [2, 4],
    },
    {
        id: 8,
        code: "EC108",
        name: "Sistemas Digitais",
        totalHours: 90,
        period: 2,
        active: false,
        viewed: false,
        requirements: [4],
    },
    {
        id: 9,
        code: "EC109",
        name: "Programação II",
        totalHours: 90,
        period: 2,
        active: false,
        viewed: false,
        requirements: [3],
    },
    {
        id: 10,
        code: "EC110",
        name: "Eletrônica Analógica",
        totalHours: 90,
        period: 3,
        active: false,
        viewed: false,
        requirements: [5],
    },
    {
        id: 11,
        code: "EC111",
        name: "Banco de Dados",
        totalHours: 60,
        period: 3,
        active: false,
        viewed: false,
        requirements: [6],
    },
    {
        id: 12,
        code: "EC112",
        name: "Redes de Computadores",
        totalHours: 90,
        period: 3,
        active: false,
        viewed: false,
        requirements: [],
    },
    {
        id: 13,
        code: "EC113",
        name: "Engenharia de Software",
        totalHours: 90,
        period: 3,
        active: false,
        viewed: false,
        requirements: [],
    },
    {
        id: 14,
        code: "EC114",
        name: "Sistemas Operacionais",
        totalHours: 90,
        period: 3,
        active: false,
        viewed: false,
        requirements: [],
    },
    {
        id: 15,
        code: "EC115",
        name: "Probabilidade e Estatística",
        totalHours: 60,
        period: 4,
        active: false,
        viewed: false,
        requirements: [7],
    },
    {
        id: 16,
        code: "EC116",
        name: "Inteligência Artificial",
        totalHours: 90,
        period: 4,
        active: false,
        viewed: false,
        requirements: [],
    },
    {
        id: 17,
        code: "EC117",
        name: "Computação Gráfica",
        totalHours: 90,
        period: 4,
        active: false,
        viewed: false,
        requirements: [],
    },
    {
        id: 18,
        code: "EC118",
        name: "Segurança de Dados",
        totalHours: 60,
        period: 4,
        active: false,
        viewed: false,
        requirements: [4],
    },
    {
        id: 19,
        code: "EC119",
        name: "Projeto Integrador I",
        totalHours: 90,
        period: 5,
        active: false,
        viewed: false,
        requirements: [5],
    },
    {
        id: 20,
        code: "EC120",
        name: "Projeto Integrador II",
        totalHours: 90,
        period: 6,
        active: false,
        viewed: false,
        requirements: [5],
    },
    {
        id: 21,
        code: "EC121",
        name: "Sistemas Embarcados",
        totalHours: 90,
        period: 6,
        active: false,
        viewed: false,
        requirements: [7],
    },
    {
        id: 22,
        code: "EC122",
        name: "Gestão de Projetos",
        totalHours: 60,
        period: 7,
        active: false,
        viewed: false,
        requirements: [8],
    },
    {
        id: 23,
        code: "EC123",
        name: "Arquitetura de Computadores",
        totalHours: 90,
        period: 7,
        active: false,
        viewed: false,
        requirements: [9],
    },
    {
        id: 23,
        code: "EC124",
        name: "Desenvolvimento Web",
        totalHours: 90,
        period: 7,
        active: false,
        viewed: false,
        requirements: [10],
    },
    {
        id: 24,
        code: "EC125",
        name: "Comunicação de Dados",
        totalHours: 60,
        period: 8,
        active: false,
        viewed: false,
        requirements: [10],
    },
    {
        id: 25,
        code: "EC126",
        name: "Sistemas Distribuídos",
        totalHours: 90,
        period: 8,
        active: false,
        viewed: false,
        requirements: [8],
    },
    {
        id: 26,
        code: "EC127",
        name: "Linguagens de Programação",
        totalHours: 90,
        period: 8,
        active: false,
        viewed: false,
        requirements: [8],
    },
    {
        id: 27,
        code: "EC128",
        name: "Gestão da Inovação",
        totalHours: 60,
        period: 9,
        active: true,
        viewed: true,
        requirements: [],
    },
    {
        id: 28,
        code: "EC129",
        name: "Empreendedorismo",
        totalHours: 60,
        period: 9,
        active: false,
        viewed: true,
        requirements: [],
    },
    {
        id: 29,
        code: "EC130",
        name: "Interação Humano-Computador",
        totalHours: 90,
        period: 9,
        active: false,
        viewed: false,
        requirements: [4],
    },
    {
        id: 30,
        code: "EC131",
        name: "Tópicos Avançados em Engenharia de Computação",
        totalHours: 90,
        period: 9,
        active: false,
        viewed: true,
        requirements: [20],
    },
    {
        id: 31,
        code: "EC132",
        name: "Trabalho de Conclusão de Curso I",
        totalHours: 90,
        period: 10,
        active: false,
        viewed: false,
        requirements: [25],
    },
    {
        id: 32,
        code: "EC133",
        name: "Trabalho de Conclusão de Curso II",
        totalHours: 90,
        period: 10,
        active: false,
        viewed: false,
        requirements: [25],
    },
]
